name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: xadichamahkamova
  DOCKER_PASSWORD: xadicha1810
  DOCKER_IMAGE_NAME: test
  DOCKER_IMAGE_TAG: latest

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Updated to v3
        with:
          context: .
          push: true
          tags: xadichamahkamova/test:latest
          platforms: linux/amd64,linux/arm64
