name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: xadichamahkamova
  DOCKER_PASSWORD: xadicha1810
  DOCKER_IMAGE_NAME: test
  DOCKER_IMAGE_TAG: latest

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: xadichamahkamova
          password: xadicha1810

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: xadichamahkamova/test:latest
          platforms: linux/amd64,linux/arm64
